FUNDAMENTALS_REQUIRED_FILTERS = {
    "indfmt": "INDL",
    "datafmt": "STD",
    "popsrc": "D",
    "consol": "C",
}

FUNDAMENTALS_VARIABLES = [
    "gvkey",
    "datadate",
    "fyear",
    "fyr",
    "conm",
    "conml",
    "tic",
    "cusip",
    "cik",
    "sic",
    "naics",
    "fic",
    "curcd",
    "at",
    "act",
    "lct",
    "che",
    "rect",
    "ap",
    "invt",
    "dlc",
    "dltt",
    "lt",
    "sale",
    "cogs",
    "xsga",
    "xrd",
    "xint",
    "capx",
    "emp",
    "oibdp",
    "ebit",
    "ebitda",
    "prcc_f",
    "csho",
]

RATIO_VARIABLES = [
    "cash_assets",
    "current_ratio",
    "leverage",
    "short_debt_assets",
    "long_debt_assets",
    "interest_burden_sales",
    "interest_burden_debt",
    "ap_cogs",
    "ar_sales",
    "net_trade_credit_assets",
    "ap_assets",
    "ar_assets",
    "inventory_assets",
    "cogs_sales",
    "capx_assets",
]

WINSORIZE_BY_YEAR = [
    "cash_assets",
    "current_ratio",
    "leverage",
    "short_debt_assets",
    "interest_burden_sales",
    "ap_cogs",
    "ar_sales",
    "net_trade_credit_assets",
    "ap_assets",
    "ar_assets",
    "inventory_assets",
    "cogs_sales",
]

PANEL_LAGS = [
    "cash_assets_w",
    "ap_cogs_w",
    "ar_sales_w",
    "short_debt_assets_w",
    "leverage_w",
    "interest_burden_sales_w",
    "log_assets",
    "log_sales",
    "log_cogs",
    "log_emp",
    "pagerank",
    "out_degree",
    "in_degree",
    "customer_hhi",
    "supplier_hhi",
    "supplier_low_liquidity_exposure",
    "customer_low_liquidity_exposure",
    "low_cash_indyr_p25",
]
